version: '3.8'

services:
  # Aplikasi Backend Node.js
  app:
    build: .
    container_name: gateway-nuha-app
    restart: always
    ports:
      - "3033:3033"
    environment:
      - PORT_EXPRESS=3033
      - APP_ENV=DEV
      # Override host database ke nama service 'db'
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=gateway_nuha_db
      - DB_PORT=5432
      # Override host redis ke nama service 'redis'
      - REDIS_HOST=redis://redis:6379
      # API Config (tetap sama atau sesuaikan jika perlu)
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
      - EXTERNAL_API_TOKEN=${EXTERNAL_API_TOKEN}
      - EXTERNAL_API_KEY=${EXTERNAL_API_KEY}
      - EXTERNAL_API_REFRESH_TOKEN=${EXTERNAL_API_REFRESH_TOKEN}
    depends_on:
      - db
      - redis
    networks:
      - gateway-network

  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: gateway-nuha-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gateway_nuha_db
      - TZ=Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - gateway-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: gateway-nuha-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge

